"""cringe-filter: a portable AI-cringe filter and human-voice filter.

Everything here is derived from measurements of one researcher's writing,
contrasted against text Claude wrote in the same GitHub threads. The
numbers live in data/profile.json and are regenerated by the pipeline in
a private repository; nothing in this package is hand-tuned taste.

Four things it does, each a subcommand of ``python -m cringe_filter``:

    lint     deterministic tells (dashes, formatting, frames, vocabulary),
             with the measured rate ratio and interval behind every rule
    score    how much a draft reads like Claude versus like the writer in a
             given context, feature by feature
    prompt   the voice filter as a prompt: register card, measured tells,
             the writer's phrases and real exemplars, for any model to apply
    rewrite  apply that prompt with Claude and lint the result (optional
             dependency: the anthropic package); --minimal makes the
             smallest edit a reviewer would, for a draft headed to review
"""
from .lint import lint_text, rules_for  # noqa: F401
from .score import score_text  # noqa: F401
from .prompt import build_prompt, build_minimal_prompt  # noqa: F401
from .registers import resolve, infer_context  # noqa: F401

__version__ = "0.1.0"
